### ISSUE TITLE
Smooth ERC functionality in TDLNM and Monotone TDLNM

### ISSUE THREAD

**Issue by danielmork** [danielmork/dlmtree#12] opened 2024-05-10 03:58 UTC
Functionality for smooth ERC in TDLNM and Monotone TDLNM is broken. Should allow for three options for the 'tdlnm.exposure.se' input in dlmtree():
1. scalar input (this is the default with value sd(exposure.data)/2)
2. matrix input with size equal to exposure data
3. zero (i.e., no smoothing--use size 0 matrix)
This input is then passed to tdlnm_cpp or monotdlnm_cpp with R variable model$SE as a matrix with size equal to model$X (unless no smoothing).

**Comment by SeongwonIm** [comment] 2024-05-14 18:17
The problem was caused by the tdlnm.exposure.se having NULL as the default value. I've pushed a fix in commit 725be81. Let me know if the issue is resolved. Thanks for spotting the bug!

**Comment by danielmork** [comment] 2024-05-15 02:57
Issue is not yet resolved, specifically for tdlnm.exposure.se=0. I have submitted new pull request with additional fix

**Closed** 2024-05-20 19:00 UTC
Labels: bug, invalid
